name: Nasdaq Mirror

on:
  workflow_dispatch:       # avvio manuale
  schedule:
    - cron: "0 */6 * * *"  # ogni 6 ore (riduci lo spam; cambia se vuoi)

permissions:
  contents: write          # << chiave: serve per poter fare push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download lists (robusto con fallback)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data
          curl -fsSL "https://ftp.nasdaqtrader.com/dynamic/SymbolDirectory/nasdaqlisted.txt"  -o data/nasdaqlisted.txt
          curl -fsSL "https://ftp.nasdaqtrader.com/dynamic/SymbolDirectory/otherlisted.txt"   -o data/otherlisted.txt

      - name: Commit & Push (if changed)
        shell: bash
        run: |
          set -e
          if git diff --quiet --exit-code -- data/ ; then
            echo "No changes."; exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/nasdaqlisted.txt data/otherlisted.txt
          git commit -m "Mirror update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
