name: Nasdaq Mirror

on:
  schedule:
    - cron: "0 */6 * * *"   # ogni 6 ore (regola tu)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download lists (con fallback)
        shell: bash
        run: |
          set -euo pipefail

          # nasdaqlisted.txt
          curl -fsSL --max-time 25 \
            "http://www.nasdaqtrader.com/dynamic/symboldirectory/nasdaqlisted.txt" \
            -o nasdaqlisted.txt || \
          curl -fsSL --max-time 25 \
            "https://raw.githubusercontent.com/Sandrito78/razzi-nasdaq-mirror/main/nasdaqlisted.txt" \
            -o nasdaqlisted.txt

          # otherlisted.txt
          curl -fsSL --max-time 25 \
            "http://www.nasdaqtrader.com/dynamic/symboldirectory/otherlisted.txt" \
            -o otherlisted.txt || \
          curl -fsSL --max-time 25 \
            "https://raw.githubusercontent.com/Sandrito78/razzi-nasdaq-mirror/main/otherlisted.txt" \
            -o otherlisted.txt

      - name: Commit & Push
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add nasdaqlisted.txt otherlisted.txt
          git commit -m "Mirror update" || echo "No changes"
          git push
