name: Nasdaq Mirror

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download lists (HTTPS + retry + sanity check)
        run: |
          set -euo pipefail
          UA="curl/8.5.0"
          download () {
            url="$1"; out="$2"
            echo "→ $url -> $out"
            curl -fsSL --retry 4 --retry-delay 2 --max-time 45 \
                 -H "User-Agent: $UA" \
                 -H "Cache-Control: no-cache" \
                 "$url" -o "$out"
          }

          download "https://www.nasdaqtrader.com/dynamic/SymbolDirectory/nasdaqlisted.txt" nasdaqlisted.txt
          download "https://www.nasdaqtrader.com/dynamic/SymbolDirectory/otherlisted.txt"   otherlisted.txt

          # file veri devono pesare > 50 KB
          test $(wc -c < nasdaqlisted.txt) -gt 50000
          test $(wc -c < otherlisted.txt)   -gt 50000

      - name: Download lists (HTTPS + retry + sanity check)
        run: |
          set -euo pipefail
          UA="Mozilla/5.0 (compatible; RazziBot/1.0)"
          download () {
            url="$1"; out="$2"
            echo "→ $url -> $out"
            curl -fsSL --retry 4 --retry-delay 2 --max-time 60 \
                 -H "User-Agent: $UA" \
                 -H "Cache-Control: no-cache" \
                 "$url" -o "$out"
          }
      
          download "https://www.nasdaqtrader.com/files/SymbolDirectory/nasdaqlisted.txt" nasdaqlisted.txt
          download "https://www.nasdaqtrader.com/files/SymbolDirectory/otherlisted.txt"   otherlisted.txt
      
          # i file veri hanno tante righe; richiedi almeno 500 righe per sicurezza
          test $(wc -l < nasdaqlisted.txt) -gt 500
          test $(wc -l < otherlisted.txt)   -gt 500
