name: Nasdaq Mirror

on:
  schedule:
    - cron: "*/5 * * * *"   # ogni 5 minuti
  workflow_dispatch:        # per avviarlo anche a mano

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download nasdaqlisted.txt
        run: |
          curl -s -L "http://ftp.nasdaqtrader.com/dynamic/SymbolDirectory/nasdaqlisted.txt" -o nasdaqlisted.txt
          curl -s -L "http://ftp.nasdaqtrader.com/dynamic/SymbolDirectory/otherlisted.txt" -o otherlisted.txt

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add nasdaqlisted.txt otherlisted.txt
          git commit -m "Update Nasdaq lists" || echo "No changes"
          git push
