name: Nasdaq Mirror

on:
  workflow_dispatch:   # puoi lanciarlo a mano
  schedule:
    - cron: '0 */6 * * *'   # ogni 6 ore

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create data dir
        run: mkdir -p data

      - name: Fetch Nasdaq Listed
        run: |
          curl -s https://www.nasdaqtrader.com/dynamic/symdir/nasdaqlisted.txt -o data/nasdaqlisted.txt
          curl -s https://www.nasdaqtrader.com/dynamic/symdir/otherlisted.txt -o data/otherlisted.txt

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/nasdaqlisted.txt data/otherlisted.txt
          git diff --cached --quiet || git commit -m "Update Nasdaq lists"
          git push
