name: Nasdaq Mirror

permissions:
  contents: write

on:
  workflow_dispatch:        # avvio manuale
  schedule:
    - cron: "0 */6 * * *"   # ogni 6 ore (regola tu)

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Download lists (robusto con fallback)
        run: |
          set -e
          curl -sL "http://ftp.nasdaqtrader.com/dynamic/SymbolDirectory/nasdaqlisted.txt" -o nasdaqlisted.txt || true
          curl -sL "http://ftp.nasdaqtrader.com/dynamic/SymbolDirectory/otherlisted.txt" -o otherlisted.txt || true
          # se FTP non va, prova HTTPS (alcune reti lo preferiscono)
          if [ ! -s nasdaqlisted.txt ]; then
            curl -sL "https://www.nasdaqtrader.com/dynamic/SymbolDirectory/nasdaqlisted.txt" -o nasdaqlisted.txt || true
          fi
          if [ ! -s otherlisted.txt ]; then
            curl -sL "https://www.nasdaqtrader.com/dynamic/SymbolDirectory/otherlisted.txt" -o otherlisted.txt || true
          fi

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add nasdaqlisted.txt otherlisted.txt
          git commit -m "Mirror update" || echo "No changes"
          git push origin HEAD:main
