name: Nasdaq Mirror

on:
  workflow_dispatch:       # avvio manuale
  schedule:
    - cron: "0 */6 * * *"  # ogni 6 ore (riduci lo spam; cambia se vuoi)

permissions:
  contents: write          # << chiave: serve per poter fare push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download lists (mirror-first con fallback e retry)
        shell: bash
        run: |
          # niente -e qui: non vogliamo abortire il passo per un singolo curl
          set -u -o pipefail
          mkdir -p data

          fetch() {
            local out="$1"; shift
            local tmp="$out.tmp"
            : > "$tmp" || true

            for u in "$@"; do
              echo "➡️  Provo $u"
              # retry “manuale” + curl retry per robustezza
              for i in 1 2 3; do
                # NB: niente -f; intercettiamo noi l'errore
                if curl -sS --connect-timeout 10 --max-time 90 \
                     --retry 3 --retry-all-errors \
                     -H 'User-Agent: Mozilla/5.0' -H 'Accept: text/plain' \
                     "$u" -o "$tmp"; then
                  # Valida: deve avere almeno qualche '|' o l'header
                  if grep -qE '(^Symbol\|Security Name)|\|' "$tmp"; then
                    mv "$tmp" "$out"
                    echo "✅ OK da $u → salvato in $out"
                    return 0
                  else
                    echo "⚠️  Contenuto non valido da $u (niente pipe). Ritento/altro URL…"
                  fi
                else
                  rc=$?
                  echo "❌ curl fallito (rc=$rc) da $u (tentativo $i/3)."
                fi
                sleep 2
              done
            done

            rm -f "$tmp" 2>/dev/null || true
            echo "⚠️  Tutte le sorgenti fallite per $out. Mantengo file precedente se esiste."
            # NON fallire lo step
            return 0
          }

          # nasdaqlisted prima dal tuo mirror, poi Nasdaq
          fetch data/nasdaqlisted.txt \
            "https://raw.githubusercontent.com/Sandrito78/razzi-nasdaq-mirror/main/data/nasdaqlisted.txt" \
            "https://www.nasdaqtrader.com/files/SymbolDirectory/nasdaqlisted.txt" \
            "https://ftp.nasdaqtrader.com/dynamic/SymbolDirectory/nasdaqlisted.txt"

          # otherlisted idem
          fetch data/otherlisted.txt \
            "https://raw.githubusercontent.com/Sandrito78/razzi-nasdaq-mirror/main/data/otherlisted.txt" \
            "https://www.nasdaqtrader.com/files/SymbolDirectory/otherlisted.txt" \
            "https://ftp.nasdaqtrader.com/dynamic/SymbolDirectory/otherlisted.txt"


      - name: Commit & Push (safe rebase)
        shell: bash
        run: |
          set -euo pipefail
  
          # Config Git
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config pull.rebase true
  
          # Aggiungi solo se ci sono cambi
          git add -A
          if git diff --cached --quiet; then
            echo "Nessuna modifica da committare."
            exit 0
          fi
  
          git commit -m "Mirror update"
  
          # Evita rifiuti per divergenze: rebase sul main remoto
          git fetch origin main
          git rebase origin/main
  
          # Push con piccolo retry in caso di race
          n=0
          until [ $n -ge 3 ]; do
            if git push origin HEAD:main; then
              echo "Push riuscito."
              exit 0
            fi
            n=$((n+1))
            echo "Push fallito (tentativo $n). Pull --rebase e ritento..."
            git pull --rebase origin main || true
            sleep 2
          done
  
          echo "Push fallito dopo 3 tentativi."
          exit 1
